---
# flag to install or skip docker module installation and configuration
install_docker: true

# docker
docker__channel: ["stable"]
docker__version: "19.03.5"
docker__state: "present"
docker__compose_version: "1.25.0"
docker__users: ["{{default_username}}"]
docker__daemon_flags:
  - "-H unix://"
  #- "-H unix:// --iptables=false"
# "a" removes unused images (useful in production).
# "f" forces it to happen without prompting you to agree.
docker__cron_jobs_prune_flags: "af"
docker__cron_jobs:
  - name: "Docker disk clean up"
    job: "docker system prune -{{docker__cron_jobs_prune_flags}} > /dev/null 2>&1"
    schedule: ["0", "0", "*", "*", "0"]
    cron_file: "docker-disk-clean-up"
    user: "{{(docker__users | first) | d('root')}}"
    state: "present"
